### ISSUE TITLE
[BUG] Doesn't open outfits for fivem-appearance

### ISSUE THREAD

**Issue by w4fflz** [Marttins011/mt-clothingbag#1]
I have changed the config to pull from fivem-appearance but the clothing outfits don't show when using the item.  QB-Clothing works fine

**Comment by Marttins011** [comment]
Hey! Try using fivem-appearance with qb-clothing at config.lua

**Comment by SirOMGitsYOU** [comment]
> Hey! Try using fivem-appearance with qb-clothing at config.lua

Have tried this myself but it doesn't seem to open any menus and no f8 or console errors

**Comment by Marttins011** [comment]
Hey! This is fixed, just redownload all script and done

**Comment by w4fflz** [comment]
I just redownloaded but don't see a config file anymore?  Do I just change the qb-clothing event in the client.lua? Or how do I make it work with Fivem-appearance?  I don't have qb-clothing installed in my server anywhere anymore

**Comment by SirOMGitsYOU** [comment]
> I just redownloaded but don't see a config file anymore? Do I just change the qb-clothing event in the client.lua? Or how do I make it work with Fivem-appearance? I don't have qb-clothing installed in my server anywhere anymore

Config option not required for fivem-appearance as it's backwards compatible events so the qb-clothing event will work regardless
