### ISSUE TITLE
[Suggestion] QOL Improvement and feature suggestion/change

### ISSUE THREAD

**Issue by SirOMGitsYOU** [Marttins011/mt-clothingbag#3]
Would it be possible to have your character place the bag directly on the floor for you to be able to share the third-eye option with others to use the outfit changing menu (obviously this would bring up the player's own individual outfit menu)? However, for gearing up for heists, only one player must bring a backpack. 

Is there any way to force the place to equip the duffle bag attachment when holding this in the inventory which would make more RP sense as he's not shoving the bag in the prison pocket

**Comment by SirOMGitsYOU** [comment]
Has this been implemented? @Marttins011?

**Comment by Marttins011** [comment]
No, at this moment the script is like i want, i'll not change anything for now.
